### ISSUE TITLE
Thread-safety of Soundex.For()

### ISSUE THREAD

**Issue by ghost** [rsingh85/SoundexAlgorithm#2]
The Soundex class is a static class. Therefore the For() method is static as well. However, as far as I can see, no attempts have been made to make the method thread-safe.
My suggestion: make it thread-safe but don't make it static. If we can create one instance per worker thread, it can be used in a multi-threaded application without problems.
Related: https://stackoverflow.com/questions/5839974/are-static-classes-thread-safe

**Comment by rsingh85** [comment]
Hi, thanks for the feedback. Making it static was a bad decision as I didn't think of multi-threaded clients - updated the code and now the class and For method are no longer static. When I have more time I'll also revisit the unit tests to get a better separation and coverage.

**Comment by rsingh85** [comment]
I've also sealed the class as I can't see a good reason to inherit from it - I'm open to feedback on this if you disagree. Thanks.

**Comment by ghost** [comment]
I didn't need to inherit from it until now. Also, according to the clean code principle "favor composition over inheritance" I don't like inheritance that much. So for me, sealed is fine.

**Comment by rsingh85** [comment]
Cool. Thanks, i'll close the issue.
